### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mugi789** [schollz/getsong#5]
2) Getting 'Menjadi Indonesia' by 'Pandai Besi'..{"level":"debug","time":"2019-12-25T16:11:55+07:00","message":"Fetching https://www.youtube.com/watch?v=0-fnVhzIPtY"}
[error]	2019/12/25 16:12:04 getsong.go:153: No audio available
..error: could not download video: No audio available

**Comment by kenpokas** [comment]
the link please???
