### ISSUE TITLE
Failing Build: cannot use f (type *ytdl.Format) as type ytdl.Format in assignment

### ISSUE THREAD

**Issue by n8jadams** [schollz/getsong#6]
When I try to `go get` this package, or when I try to import it in a golang script I see the following error

```
# github.com/schollz/getsong
/go/src/github.com/schollz/getsong/getsong.go:239:14: cannot use f (type *ytdl.Format) as type ytdl.Format in assignment
/go/src/github.com/schollz/getsong/getsong.go:248:43: cannot use *format (type ytdl.Format) as type *ytdl.Format in argument to info.GetDownloadURL

```

My golang skills are too weak to fix this...

**Comment by cw1nte** [comment]
Same seen here, MacOS 10.11.6, brand new install of go by brew seemed fine although there were
excessive wakes noted in system logging
go_2020-01-13-112629_<user>.wakeups_resource.diag:
Command:         go
Path:            /usr/local/Cellar/go/1.13.6/bin/go
Version:         ??? (???)
Parent:          ruby [51879]
Responsible:     iTerm2 [535]
PID:             53120

Event:           wakeups (microstackshots only)
Wakeups:         2255 wakeups per second for 20 seconds
Duration:        20.00s
Steps:           20

Hardware model:  MacBookPro11,5
Active cpus:     8

**Comment by cw1nte** [comment]
Just before that also:
process go_bootstrap[52572] caught causing excessive wakeups. Observed wakeups rate (per sec): 2792

**Comment by cw1nte** [comment]
Now rebuilt and seems fixed! (26 Jan 2020)
