### ISSUE TITLE
package github.com/schollz/progressbar/v2: cannot find package

### ISSUE THREAD

**Issue by ipmanlk** [schollz/getsong#9]
Library is not downloading and produces this error,
package github.com/schollz/progressbar/v2: cannot find package "github.com/schollz/progressbar/v2"

**Comment by newkit** [comment]
+1

**Comment by 5c0tt-b0t** [comment]
+3
Exact same problem here too!

**Comment by prologic** [comment]
Fixed in prologic/getsong@2b26054

**Comment by 5c0tt-b0t** [comment]
**stderr:**

```bash
$ go get -u www.github.com/schollz/getsong.git

package github.com/scholl/progressbar/v2: cannot find package "github.com/schollz/progressbar/v2" in any of:
        /data/data/com.termux/files/usr/lib/go/src/github.com/schollz/progressbar/v2 (from $GOROOT)
        /data/data/com.termux/files/home/go/src/github.com/schollz/progressbar/v2 (from $GOPATH)
```

Thank you! this looks amazing! unfortunately, I am unable to use it still because of the progress bar.
Any help is truly appreciated! Thank you.

**Comment by prologic** [comment]
> Fixed in [prologic/getsong@2b26054](https://github.com/prologic/getsong/commit/2b26054)

@5c0tt-b0t ☝️

**Comment by 5c0tt-b0t** [comment]
I apologise @prologic , I have done uninstalled / reinstalled so thought (fresh install) would remedy this. I see the commits you pointed out, if my fresh install doesnt work then do I manually download these changed files and replace? or is there an internal update command? sorry, I am totally inexperienced when it comes to Go.

**Comment by prologic** [comment]
You can:

```#!sh
go get github.com/prologic/getsong/...
```
